# Generated by Django 5.0.1 on 2024-02-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProyecto', models.CharField(max_length=255)),
                ('nomCliente', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('En Curso', 'En Curso'), ('Stand By', 'Stand By'), ('Terminado', 'Terminado')], max_length=20)),
            ],
        ),
    ]
